"""Add Flights

Revision ID: 5c3db42a6084
Revises: e88172c58e58
Create Date: 2023-07-17 07:24:08.868979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3db42a6084'
down_revision = 'e88172c58e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
