"""Trying again

Revision ID: 62f03ab23517
Revises: be0fb2c308e0
Create Date: 2023-07-17 11:33:57.406013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f03ab23517'
down_revision = 'be0fb2c308e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
