"""added pilots to flights again

Revision ID: 69db494b7ed9
Revises: 80a1b2dc3304
Create Date: 2023-07-19 17:03:07.092990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69db494b7ed9'
down_revision = '80a1b2dc3304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
