"""flight:reservation -- one:many

Revision ID: 7d61902616c4
Revises: 16300b6e9b1d
Create Date: 2023-07-18 21:00:57.850369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d61902616c4'
down_revision = '16300b6e9b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
