"""add pilot id to flights?

Revision ID: 80a1b2dc3304
Revises: 7d61902616c4
Create Date: 2023-07-19 16:45:21.660574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a1b2dc3304'
down_revision = '7d61902616c4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pilot_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('session_id', 'pilots', ['pilot_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pilot_id')
    # ### end Alembic commands ###
